language: node_js
node_js:
    - "stable"
cache:
    yarn: true
    directories:
        - node_modules

script:
    - yarn test
    - yarn build

env: SENTRY_ORG=my-app-1o SENTRY_PROJECT=my-app SENTRY_ENVIRONMENT=production

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
        branch: main

after_deploy: |
    curl -sL https://sentry.io/get-cli/ | bash
    export SENTRY_RELEASE=$(sentry-cli releases propose-version)
    sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
    sentry-cli releases set-commits $SENTRY_RELEASE --auto
    sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps build/static/js
    sentry-cli releases finalize $SENTRY_RELEASE
    sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
