language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
scripts:
    - npm test
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
        branch: main

jobs:
    include:
        - name: Create release and notify Sentry of deploy
            env: SENTRY_ORG=my-app-1o SENTRY_PROJECTmy-app SENTRY_ENVIRONMENT=production
            script: |
                curl -sL https://sentry.io/get-cli/ | bash
                export SENTRY_RELEASE=$(sentry-cli releases propose-version)
                sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
                sentry-cli releases set-commits $SENTRY_RELEASE --auto
                sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps build/static/js
                sentry-cli releases finalize $SENTRY_RELEASE
                sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
